langague: java

script:
  - mvn dependency:go-offline
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - docker build -t api
  - docker build -t db_changelog
  - docker run -it api
  - docker run -it db_changelog
  #- echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - $HOME/.m2
