langague: java

script:
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - mvn clean verify
  - mvn package -Dskiptest
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t arthurliger/devops:api sample-application-http-api-server
  - docker build -t arthurliger/devops:db_changelog sample-application-db-changelog-job
  - docker push arthurliger/devops:api
  - docker push arthurliger/devops:db_changelog


addons:
  sonarcloud:
    organization: "ligerarthur" # the key of the org you chose at step #3
    token:
      secure: $SONARCLOUD_PASS # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo



cache:
  directories:
    - $HOME/.m2
