langague: java

jobs:
  include:
    - stage: "Test"
      name: "Test "
      script: 
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ligerarthur_sample-application-students

    - stage: "Deploy"
      name: "Déploiement"
      script: 
      - mvn clean verify
      - mvn package -Dskiptest
      - docker build -t arthurliger/devops:api sample-application-http-api-server
      - docker build -t arthurliger/devops:db_changelog sample-application-db-changelog-job
      - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push arthurliger/devops:api
      - docker push arthurliger/devops:db_changelog


services:
  - docker


addons:
  sonarcloud:
    organization: "ligerarthur" # the key of the org you chose at step #3
    token:
      secure: $SONARCLOUD_PASS # encrypted value of your token





cache:
  directories:
    - $HOME/.m2
