langague: java

script:
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - mvn clean verify
  - mvn package -Dskiptest
  - docker build -t api sample-application-http-api-server
  - docker build -t db_changelog sample-application-db-changelog-job

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

cache:
  directories:
    - $HOME/.m2
