langague: java

script:
  - mvn dependency:go-offline
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
cache:
  directories:
    - $HOME/.m2
