langague: java

script:
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - mvn clean verify
  - mvn package -Dskiptest
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t arthurliger/devops:api sample-application-http-api-server
  - docker build -t arthurliger/devops:db_changelog sample-application-db-changelog-job
  - docker push arthurliger/devops:api
  - docker push arthurliger/devops:db_changelog



cache:
  directories:
    - $HOME/.m2
