langague: java

script:
  - mvn dependency:go-offline
  - mvn clean verify

env:
  global:
    - secure: $DOCKER_PASS

services:
  - docker

before_install:
  - docker login --username arthurliger
  - echo '${DOCKER_PASS}'

cache:
  directories:
    - $HOME/.m2
